name: CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: Download Conan package manager.
      run: |
        pwd
        pip3 install wheel setuptools
        pip3 install conan
        export PATH=$PATH:/home/runner/.local/bin
        echo $PATH
        conan --version
        ls
    - name: configure
      run: |
        export PATH=$PATH:/home/runner/.local/bin
        echo $PATH
        mkdir build
        cd build
        conan install ..
        cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_DOCS=OFF ..
    - name: build
      run: |
        cd build
        make 
    - name: test
      run: cd build && ctest
